### ISSUE TITLE
[BUG] 戳一戳的 target_id 缺失

### ISSUE THREAD

**Issue by Yiwen-Chan** [yuudi/gypsum#8]
github.com/wdvxdr1123/ZeroBot v0.0.0-20210222145945-329707c6a35a
这个版本中的 Event 中并没有 target_id 字段
导致无法在 gypsum 中判断戳一戳的目标 QQ

**Comment by Yiwen-Chan** [comment]
ZeroBot新版本中已经修复了此问题，但是变动过大，不适宜直接更新依赖

**Comment by Yiwen-Chan** [comment]
问题解决

**Comment by yuudi** [comment]
目前 develop 分支使用的是 zerobot 1.0，不过 develop 分支有一些问题没有处理完，可能有未知 bug
